#!/bin/bash

DIR="$(cd "$(dirname "$0")/../Resources" && pwd)"
cd "$DIR"

# Kill any existing instance
pkill -f "file-share-app" 2>/dev/null

# Start server
./file-share-app > /tmp/sharedrop.log 2>&1 &

sleep 2

# Open browser
open "http://localhost:8080"

# Show notification
osascript -e 'display notification "Server running at http://localhost:8080" with title "ShareDrop Started"'
